"""Encoder registry for stage 2 models."""
from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class Stage2ModelProtocol(Protocol):
    def forward(self, *args: Any, **kwargs: Any) -> Any: ...
    def forward_with_cfg(self, *args: Any, **kwargs: Any) -> Any: ...
    def forward_with_internalguidance(self, *args: Any, **kwargs: Any) -> Any: ...
    def forward_with_ig_and_cfg(self, *args: Any, **kwargs: Any) -> Any: ...
    def train(self, mode: bool = True) -> Any: ...
    def eval(self) -> Any: ...
