target: ifid.vae.flux2vae.Flux2VAEResflow
params:
  ckpt_path: Comfy-Org/flux2-dev/split_files/vae/flux2-vae.safetensors
  resolution: 256
  strict: true
  size: medium
  flow_ckpt_path: ./checkpoints/0100000.pt