target: ifid.vae.svg.SVGEXPORT
params:
  ckpt_path: /share/xutongda/hfhome/hub/SVG/autoencoder/svg_autoencoder_dinov3s16p_vit-s_epoch40.ckpt
  embed_dim: 32
  ddconfig:
    double_z: true
    z_channels: 392
    resolution: 256
    in_channels: 3
    out_ch: 3
    ch: 128
    ch_mult: [1,1,2,2,4]
    num_res_blocks: 2
    attn_resolutions:
    - 16
    dropout: 0.0
  dinoconfig:
    dinov3_location: /video_ssd/kongzishang/xutongda/git/dinov3
    model_name: dinov3_vits16plus
    weights: /video_ssd/kongzishang/xutongda/git/dinov3/dinov3_vits16plus_pretrain_lvd1689m-4057cbaa.pth
  extra_vit_config:
    output_dim: 8
    mask_ratio: 0.1
    use_outnorm: true
