target: ifid.vae.uae.UAEVAE
params:
  ckpt_path: weepiess2383/UAE/checkpoints/DINOv2-B/ep-last.pt
  uae_config:
    encoder_cls: 'Dinov2withNorm'
    encoder_config_path: 'facebook/dinov2-with-registers-base'
    encoder_input_size: 224
    encoder_params:
      dinov2_path: 'facebook/dinov2-with-registers-base'
      normalize: true
    decoder_config_path: './ifid/vae/unified_ae/'
    noise_tau: 0.0
    reshape_to_2d: true
